import { ParseError } from "./errors";
import type { ParsedFields } from "./fields";
import { decodeEntities, htmlToText } from "./html";
import { parsePaisa } from "./money";
import { parseNabilTimestamp } from "./time";

/**
 * Nabil parser: an HTML table (spec 5.2).
 *
 *   | Transaction Date | Transaction Type | Transaction Amount | Available Balance | Remarks |
 *   | 2026-03-12 10:05 | Debit            | 1,250.00           | 6,060.55          | MPAY FPQR,71104582WxYz,ORCHID STATIONERS PVT. LTD. KTM |
 *
 * Read with HTMLRewriter rather than a regex over the markup. Bank HTML is
 * generated by a mail template, so tag soup, inline styles and wrapper spans
 * around the cell text are all likely; a streaming parser survives that where a
 * regex over `<td>(.*?)</td>` does not.
 *
 * Columns are located by their header text, not by position, so a bank that adds
 * a column fails loudly on a missing header instead of quietly reading the
 * balance out of the wrong cell.
 */

const ACCOUNT = /account\s*(?:number|no\.?|#)?\s*:?\s*([0-9A-Za-z*]*[0-9X*][0-9A-Za-z*]{5,})/i;

interface Row {
  cells: string[];
}

class TableCollector {
  readonly rows: Row[] = [];
  private current: Row | null = null;
  private cell: string | null = null;

  readonly row = {
    element: (element: Element) => {
      const row: Row = { cells: [] };
      this.rows.push(row);
      this.current = row;
      element.onEndTag(() => {
        this.current = null;
      });
    },
  };

  readonly cellElement = {
    element: (element: Element) => {
      this.cell = "";
      element.onEndTag(() => {
        this.current?.cells.push(decodeEntities(this.cell ?? "").replace(/\s+/g, " ").trim());
        this.cell = null;
      });
    },
  };

  readonly cellText = {
    text: (chunk: Text) => {
      if (this.cell !== null) this.cell += chunk.text;
    },
  };
}

async function collectTable(html: string): Promise<Row[]> {
  const collector = new TableCollector();

  const transformed = new HTMLRewriter()
    .on("tr", collector.row)
    .on("td", collector.cellElement)
    .on("th", collector.cellElement)
    // A text handler on `td` already fires for text inside nested elements, so
    // the wrapper spans bank mail templates add cost nothing here. Adding a
    // `td *` handler as well double-counts them: "Credit" arrives as
    // "CreditCredit".
    .on("td", collector.cellText)
    .on("th", collector.cellText)
    .transform(new Response(html));

  // HTMLRewriter is lazy: the handlers do not run until the body is consumed.
  await transformed.arrayBuffer();

  return collector.rows;
}

const HEADERS = {
  occurred_at: /transaction\s*date/i,
  direction: /transaction\s*type/i,
  amount: /transaction\s*amount/i,
  balance: /available\s*balance/i,
  remarks: /remark/i,
} as const;

type ColumnName = keyof typeof HEADERS;

function locateColumns(rows: Row[]): { index: Record<ColumnName, number>; headerRow: number } {
  for (let i = 0; i < rows.length; i++) {
    const cells = rows[i].cells;
    const index = {} as Record<ColumnName, number>;
    let found = 0;

    for (const [name, pattern] of Object.entries(HEADERS) as [ColumnName, RegExp][]) {
      const position = cells.findIndex((cell) => pattern.test(cell));
      if (position !== -1) {
        index[name] = position;
        found++;
      }
    }

    // Remarks is the one optional column: without it the event still reconciles,
    // it just falls back to a hash-derived event_id.
    if (found >= 4 && index.occurred_at !== undefined && index.balance !== undefined) {
      return { index, headerRow: i };
    }
  }

  throw new ParseError("table", "no Nabil transaction table header found in the HTML part");
}

export async function parseNabilHtml(html: string): Promise<ParsedFields> {
  const rows = await collectTable(html);
  const { index, headerRow } = locateColumns(rows);

  const needed = Math.max(...Object.values(index));
  const data = rows.slice(headerRow + 1).find((row) => row.cells.length > needed);
  if (data === undefined) {
    throw new ParseError("table", "transaction table has a header but no data row");
  }

  const cell = (name: ColumnName): string | null => {
    const position = index[name];
    return position === undefined ? null : (data.cells[position] ?? null);
  };

  const direction = cell("direction");
  if (direction === null || !/^(debit|credit)$/i.test(direction)) {
    throw new ParseError("direction", `expected Debit or Credit, got ${JSON.stringify(direction)}`);
  }

  const amount = cell("amount");
  const balance = cell("balance");
  const occurred = cell("occurred_at");
  if (amount === null || balance === null || occurred === null) {
    throw new ParseError("table", "transaction row is missing a required cell");
  }

  const accountMatch = ACCOUNT.exec(htmlToText(html));
  if (accountMatch === null) {
    throw new ParseError("account_label", "no account number in the message body");
  }

  return {
    account_label: accountMatch[1],
    direction: direction.toLowerCase() === "debit" ? "DEBIT" : "CREDIT",
    amount_paisa: parsePaisa(amount, "amount_paisa"),
    reported_balance_paisa: parsePaisa(balance, "reported_balance_paisa"),
    occurred_at: parseNabilTimestamp(occurred),
    ...parseRemarks(cell("remarks")),
  };
}

/**
 * Remarks are positional, like NIMB's detail blob, but richer:
 * `MPAY FPQR,71104582WxYz,ORCHID STATIONERS PVT. LTD. KTM` is method, then
 * reference, then merchant. The merchant can itself contain commas, so
 * everything after the reference is rejoined rather than taking one token.
 */
function parseRemarks(remarks: string | null): { reference: string | null; merchant: string | null } {
  if (remarks === null || remarks.trim() === "") return { reference: null, merchant: null };

  const tokens = remarks.split(",").map((token) => token.trim());
  if (tokens.length < 2) {
    // A single token is a method code with nothing after it; there is no
    // reference to be had, so the event_id falls back to the hash derivation.
    return { reference: null, merchant: null };
  }

  const reference = tokens[1] !== "" ? tokens[1] : null;
  const merchant = tokens.length > 2 ? (tokens.slice(2).join(", ").trim() || null) : null;
  return { reference, merchant };
}
